version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_chat
    mem_limit: 256m
    ports:
         - '8080:8080'
    depends_on:
      - mariadb # MariaDB가 시작된 후에 backend 시작
    networks:
      - chat-network
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: unless-stopped # 컨테이너가 중지되지 않은 경우에만 재시작합니다.
    container_name: mariadb
    # 최대 메모리양 설정 : 128m : 적은양 간단한 작업식 적절
    mem_limit: 128m
#    expose:
#      - 3306
    ports:
      - '3307:3306'
    volumes:
      - ./mariadb/maria_data:/var/lib/mysql
      - ./mariadb/sqls/:/docker-entrypoint-initdb.d/
    # 환경 변수 셋팅시에는 `-` 는 생략한다.
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      TZ: ${TIME_ZONE}
    networks:
      - chat-network
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
#    ports:
#      - '6379:6379'
    volumes:
      - ./redis/redis_data/:/data/
      - ./redis/my-redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - chat-network
networks:
  chat-network:
    name: chat-network
    driver: bridge
